version: "3"

services:
  zookeeper:
    image: zookeeper:3.4.14

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    hostname: localhost
    ports:
      - "9092:9092"

  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: donotuseinproduction123
    ports:
      - "5432:5432"
